name = "sigmacode-ai-triggers"
main = "ai-trigger-worker.ts"
compatibility_date = "2024-09-01"

# KV Namespace for trigger storage
[[kv_namespaces]]
binding = "AI_TRIGGERS_KV"
id = "${AI_TRIGGERS_KV_ID}"
preview_id = "${AI_TRIGGERS_KV_PREVIEW_ID}"

# Environment Variables
[vars]
ENV = "production"

# Secrets (set via wrangler secret put)
# BACKEND_URL
# BACKEND_API_KEY
# SUPABASE_URL
# SUPABASE_KEY
# DIFY_API_URL

# Cron Triggers for scheduled agents
[triggers]
crons = ["*/15 * * * *"]  # Run every 15 minutes

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
