#!/bin/bash
# Sigmacode2 Demo - zeigt wie alles funktioniert

echo "🚀 Sigmacode2 Agent-Firewall Demo"
echo ""
echo "📋 Was du hast:"
echo "✅ DAC-Implementierung vollständig"
echo "✅ 3 Demo-Agenten in DB:"
echo "   - demo-agent-dify-basic (Firewall aus)"
echo "   - demo-agent-superagent-enforce (Firewall strikt)"
echo "   - demo-agent-shadow-compare (Shadow-Mode)"
echo "✅ Test-Skripts bereit"
echo "✅ Firewall-Stream (SSE)"
echo ""
echo "🛠️  Services starten:"
echo "1. PostgreSQL: docker run --name postgres-dev -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=sigmacode_dev -p 5432:5432 -d postgres:15"
echo "2. Next.js: pnpm dev"
echo "3. Dify: cd dify/docker && docker-compose up -d"
echo "4. Superagent: cd superagent && docker-compose up -d"
echo ""
echo "🧪 Tests ausführen:"
echo "1. Firewall-Stream: curl -N http://localhost:3000/api/firewall/stream"
echo "2. Basic Agent: curl -X POST http://localhost:3000/api/agents/demo-agent-dify-basic/invoke -H 'Content-Type: application/json' -d '{\"input\": \"Hallo!\", \"context\": {\"demo\": true}}'"
echo "3. Secure Agent: curl -X POST http://localhost:3000/api/agents/demo-agent-superagent-enforce/invoke -H 'Content-Type: application/json' -d '{\"input\": \"GitHub Suche\", \"context\": {\"repo\": \"Sigmacode2\"}}'"
echo ""
echo "🎯 Erwartete Events im Stream:"
echo "- event: hello (Stream startet)"
echo "- event: firewall (bei Agent-Aufrufen)"
echo "  - phase: pre/post/shadow/error"
echo "  - backend: dify/superagent"
echo "  - status: 200/403/500"
echo ""
echo "✅ Alles bereit zum Testen! 🔥"
