name: Deploy Backend to Render

on:
  push:
    branches: [main, production]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          if [ -n "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
            echo "✅ Render deployment triggered"
          else
            echo "⚠️ RENDER_DEPLOY_HOOK not configured"
            echo "Please set up deploy hook in Render.com and add to GitHub Secrets"
          fi

      - name: Wait for deployment
        run: |
          echo "⏳ Waiting 60s for deployment to start..."
          sleep 60

      - name: Health Check
        run: |
          max_attempts=10
          attempt=0
          
          while [ $attempt -lt $max_attempts ]; do
            echo "Attempt $((attempt + 1))/$max_attempts"
            
            if curl -f https://sigmacode-backend.onrender.com/health; then
              echo "✅ Backend is healthy!"
              exit 0
            fi
            
            attempt=$((attempt + 1))
            sleep 30
          done
          
          echo "❌ Backend health check failed"
          exit 1

      - name: Notify Success
        if: success()
        run: |
          echo "🎉 Backend successfully deployed to Render!"
          echo "URL: https://sigmacode-backend.onrender.com"
